### ISSUE TITLE
[BUG]Changing all attachment names may lose

### ISSUE THREAD

**Issue by jerviscui** [JYC333/obsidian-attachment-name-formatting#14]
I found that when I insert an image in the header, all the file names below are changed once.
But it may cause the files to be lost. 
I observed that the file name was changed to `tmp...` first. My guess is that closing the file or sync upload at this point may leave the `tmp...` name there, thus causing the note can't be found in the temp file name.

Is it possible to pass another naming strategy, such as using time as the name and increasing the suffix when the name is duplicated?

**Comment by JYC333** [comment]
Sorry for the late reply, but could you elaborate on the problem in detail?

Whether you insert an image in the header or in the content, all the attachments will be checked and renamed if needed. Or what do you mean about the header?

And about the `tmp`, I think it should be fine if it stops with `tmp`. Because the file name and the link in the note both will be changed. So if it closes at some point, when you restart the app it can pick up again to rename it.

**Comment by jerviscui** [comment]
> I found that when I insert an image in the header, all the file names below are changed once.
> But it may cause the files to be lost.

1. Insert pictures in the file, Let's say they're called 1,2,3,
2. Then add a new image between 1 and 2, For example, it's called 1.5.
3. I later found out that the plugin renames all files after 1.5, but in the process may cause files to be lost.

When I discovered this problem, I had over ten images in my file.

**Comment by JYC333** [comment]
Hi, now this bug is fixed in 1.6.3.

**Comment by juestchaos** [comment]
Well done, I need for this +1
