### ISSUE TITLE
#22 not fixed

### ISSUE THREAD

**Issue by calmwaves111** [JYC333/obsidian-attachment-name-formatting#23]
Has the bug #22  really been fixed？I still meet this error in version 1.9.5. and I go back to 1.9.3, there won't be any problems. I think it was an error caused by the added functionality of #20

**Comment by OGGGGGG** [comment]
I meet this error both in version 1.9.4 and 1.9.5.But issues phenomenon are different:
In version 1.9.2 there won't be any problems ，like:"/markdown directory/_resources"
In version 1.9.4 the attchments directory are wrong ，like:"/_resources"
In version 1.9.5 the bug is fixed halfway，like:"/_resources/markdown directory"

**Comment by JYC333** [comment]
Just checked again, I think it should fix now. Please raise again if there is still some problems.
