### ISSUE TITLE
keep the original file name / add to new filename

### ISSUE THREAD

**Issue by huwasm** [JYC333/obsidian-attachment-name-formatting#37]
- change the name to the note name is very good so you can easy find all the attachments to a note
- BUT add the option to keep the original attachment name, so it is included in the new name
- then you can also easy find back the attachment in other places outside the vault

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

Add original file name will introduce errors randomly in current implementation, because the plugin will parse the attachment name to know whether an attachment is renamed by this plugin already. If original file name contains character that same as connector configed in the plugin, it won't work correctly. No plans to change the implementation, sorry for the inconvenience.
