### ISSUE TITLE
Bug: This plugin doesn't work renaming image's names 

### ISSUE THREAD

**Issue by JosrJian** [JYC333/obsidian-attachment-name-formatting#41]
In the new version of Obsidian 1.5.12, this plugin can't rename any attachments at all. Hope this bug can be amended, thank you!

**Comment by moiseszarzar** [comment]
I came here to find some issue like that. This problem has occured with me. I thought it could have something to do with last Obsidian's updade. @JosrJian is right. I know that plugin developers use undocumented Obsidian features that change with each version and for this reason it is necessary to adapt them in some Obsidian updates, as happened now with this version 1.5.12.

I hope this issue will be resolved in the next sprint of this plugin, which has helped me immensely. I'm even going to make a promise. As soon as this problem is resolved, I'll buy the developer a coffee. Regardless, thanks to the developer for maintaining this excellent plugin. And it's because we use it daily that I think it's fair to actually pay something to the developer, after all, we can't want him to work for free. I know he likes development, but it's important to reward him, even so he knows that his product has added value to the lives of many people in their daily lives.

I will comment here in a few days about the coffee.

**Comment by JYC333** [comment]
Thanks for using this plugin and sorry for the inconvenience. Didn't have time work with this project for a while.

I have check with the latest Obsidian 1.6.7, looks like the plugin works properly.
