### ISSUE TITLE
Old pasted images are now missing - not created yet

### ISSUE THREAD

**Issue by prdlik007** [JYC333/obsidian-attachment-name-formatting#6]
I use very often notes with pasted screenshots.

Today I was reviewing older daily notes and I realized that in older notes (created before I started to use your plugin), some pictures are now missing. There is only info - pasted image was not created yet - click to create it. 

![image](https://user-images.githubusercontent.com/99074493/163201858-60367004-49be-4157-a1eb-b52869c8511a.png)

Why I think it is connected with your plugin, is that it started about 2 weeks ago and there was no other change in my Obsidian. And - what is strange - the 1st image in this note was renamed and has new name. The 2nd is gone and has old name.

There is no other plugin working with files in attachment folder, only yours.

It looks like when I open the note, plugin starts to rename images - few are successfuly renamed - and others are maybe deleted, maybe renamed... I can not find these missing pictures in attachment folder with even with new/old names. They are gone.

**Comment by JYC333** [comment]
Thanks for using this plugin! And sorry for the inconvenience.

I'm not sure whether it's caused by my plugin because I have also met this problem before I start my plugin. It's quite the same as what you have met. Also, some pasted images were missing when I open the vault once, I also cannot find them in the filesystem.

Since I have met the same problem with you and didn't know the reason behind this, I'm thinking probably it's not caused by this plugin. Of course, there still be some possibility caused by this plugin, I'll try whether I can reproduce this problem.

And again, sorry for the inconvenience. Hope that will not happen again.
